baseURL = "https://45.calgaryaikikai.com"
languageCode = "en-us"
title = "Calgary Aikikai"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id="G-YFZZMXQYDY"

  [params.logo]
    mobile = "images/ca.logo-large.png"
    mobile_height = "129px"
    mobile_width = "129px"
    desktop = "images/ca.logo-large.png"
    desktop_height = "388px"
    desktop_width = "388px"
    alt = "Calgary Aikikai"

  [params.homepage_meta_tags]
    meta_description = "Calgary Aikikai is celebrating 45 years of teaching aikdo to the Calgary area. Come join us as we welcome three senseis from Japan and the USA."
    meta_og_title = "Calgary Aikikai 45th Anniversay Seminar"
    meta_og_type = "website"
    meta_og_url = "https://calgaryaikikai.com"
    meta_og_description = "Calgary Aikikai is celebrating 45 years of teaching aikdo to the Calgary area. Come join us as we welcome three senseis from Japan and the USA."
    meta_twitter_card = "summary"
    meta_twitter_site = "@calgaryaikikai"
    meta_twitter_creator = "@calgaryaikikai"

[[menu.main]]
	name = "Details"
	url = "#details"
    weight = 1

[[menu.main]]
   name = "Pricing"
  url = "#pricing"
  weight = 2

[[menu.main]]
   name = "Schedule"
   url = "#schedule"
   weight = 3

[[menu.main]]
   name = "Location"
   url = "#location"
   weight = 4

[[menu.main]]
    name = "FAQs"
    url = "#faq"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
