#!/bin/sh
USER=bcalvez
HOST=calgaryaikikai.com
DIR=45.calgaryaikikai.com/

hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR} # this will delete everything on the server that's not in the local public directory 

exit 0